-- Visit Barichara — negocios reales investigados (fase 4), octubre 2026.
-- Fuentes: Google, Google Maps, TripAdvisor, Civitatis, GetYourGuide, Airbnb
-- Experiences, Rezdy y sitios oficiales — el link exacto de cada uno queda
-- en su columna source_url. Ningún dato de contacto fue inventado: donde no
-- se pudo verificar, el campo queda en null.
--
-- Todo entra con active = false (borrador) para que se revise desde /admin
-- antes de publicar. Los negocios genéricos de la carga anterior que no se
-- pudieron reconfirmar con esta investigación quedan desactivados al final
-- de este archivo (no se borran, solo se ocultan).
--
-- Ejecutar una sola vez, después de supabase/migration_03_website_instagram_source.sql.

-- ===================== HOTELES (15) =====================
insert into public.businesses
  (slug, name, category, zone, whatsapp, website, instagram, map_url, source_url, price_from, description_es, description_en, active, is_sample)
values
('casa-barichara-boutique', 'Casa Barichara Boutique', 'hotel', 'Carrera 11 # 5-18, centro', null, null, null, 'https://www.google.com/maps/search/?api=1&query=Casa+Barichara+Boutique+Barichara', 'https://www.espanol.skyscanner.com/hoteles/colombia/barichara-hoteles/casa-barichara-boutique/ht-136420429', 'Desde USD $129 por noche', 'Casa de arquitectura colonial restaurada en pleno centro de Barichara, con piscina y habitaciones de estilo boutique.', 'A restored colonial house right in central Barichara, with a pool and boutique-style rooms.', false, false),
('hotel-hicasua', 'Hicasua Hotel Boutique y Centro de Convenciones', 'hotel', 'Calle 7 No. 3-89, Barrio Sector Hospital', null, null, null, 'https://www.google.com/maps/search/?api=1&query=Hicasua+Hotel+Boutique+Barichara', 'https://www.pelecanus.com.co/trodat/hicasua', null, 'Hotel de 21 habitaciones con piscina al aire libre y jacuzzi, orientado también a eventos y convenciones pequeñas.', '21-room hotel with an outdoor pool and jacuzzi, also set up for small events and conventions.', false, false),
('casa-guati', 'Casa Guatí', 'hotel', 'Calle 10 # 10-29, Barrio La Loma', null, null, null, 'https://www.google.com/maps/search/?api=1&query=Casa+Guat%C3%AD+Barichara', 'https://www.hotels.com/ho4031236544/', null, 'Alojamiento de lujo tipo casa boutique en el barrio La Loma, con piscina, jardines y servicio de spa en sitio.', 'Luxury boutique house-style stay in the La Loma neighborhood, with a pool, gardens and on-site spa service.', false, false),
('casa-yahri', 'Casa Yahri', 'hotel', 'Calle 10 # 7-57, Barrio La Loma', '573007788897', 'yahri.com', null, 'https://www.google.com/maps/search/?api=1&query=Casa+Yahri+Barichara', 'https://mob.expedia.ae/Barichara-Hotels-Casa-Yahri.h100805149.Hotel-Information', null, 'Villa boutique de solo cuatro suites privadas en La Loma, con terrazas y piscinas individuales y vista al cañón.', 'A boutique villa with just four private suites in La Loma, each with its own terrace, pool and canyon view.', false, false),
('nativo-eco-hotel', 'Nativo Eco-Hotel / Glamping Barichara', 'hotel', 'Km 3 vía Barichara-San Gil, Vereda El Llano', '573144285317', 'nativoglamping.com', null, 'https://www.google.com/maps/search/?api=1&query=Nativo+Eco-Hotel+Barichara', 'https://www.nativoglamping.com', 'Desde USD $97 por noche', 'Eco-hotel y glamping campestre a las afueras del pueblo, con piscina, jardines y zonas de descanso rural.', 'Countryside eco-hotel and glamping on the edge of town, with a pool, gardens and rural relaxation areas.', false, false),
('macedonia-hacienda', 'Hotel Hacienda Macedonia', 'hotel', 'Km 3 vía Barichara-San Gil, Vereda El Llano', '573102557422', null, null, 'https://www.google.com/maps/search/?api=1&query=Hotel+Hacienda+Macedonia+Barichara', 'https://pelecanus.com.co/trodat/haciendamacedonia', null, 'Hacienda histórica de más de 200 años restaurada en 2013, con 16 habitaciones, piscina y fuente de agua propia.', 'A 200-plus-year-old hacienda restored in 2013, with 16 rooms, a pool and its own water spring.', false, false),
('posada-del-campanario', 'Posada Del Campanario', 'hotel', 'Calle 5 # 7-48', '573213065264', null, null, 'https://www.google.com/maps/search/?api=1&query=Posada+Del+Campanario+Barichara', 'https://www.kayak.com/Barichara-Hotels-Posada-Del-Campanario.2020344.ksp', null, 'Posada tipo bed & breakfast de 6 habitaciones en el centro de Barichara, con desayuno incluido y ambiente familiar.', 'A 6-room bed & breakfast in central Barichara, with breakfast included and a family atmosphere.', false, false),
('mision-santa-barbara', 'Hotel Misión Santa Bárbara', 'hotel', 'Calle 5 No. 9-08', null, null, null, 'https://www.google.com/maps/search/?api=1&query=Hotel+Misi%C3%B3n+Santa+B%C3%A1rbara+Barichara', 'https://es.hoteles.com/en/ho3439724352/hotel-mision-santa-barbara/', null, 'Hotel colonial de 31 habitaciones en el centro histórico, con piscina al aire libre y jardín interior.', 'A 31-room colonial hotel in the historic center, with an outdoor pool and interior garden.', false, false),
('santa-sofia-casa-boutique', 'Santa Sofía Casa Boutique', 'hotel', 'Carrera 4 # 5-70, centro histórico', null, null, null, 'https://www.google.com/maps/search/?api=1&query=Santa+Sofia+Casa+Boutique+Barichara', 'https://www.travelocity.com/es/Barichara-Hoteles-Santa-Sofia-Casa-Boutique.h104812143.Informacion-Hotel', 'Desde USD $133 por noche', 'Casa boutique de 8 habitaciones a pocos minutos a pie del parque principal, con piscina salada y jacuzzi con vista al pueblo.', 'An 8-room boutique house a short walk from the main square, with a saltwater pool and a jacuzzi overlooking the town.', false, false),
('color-de-hormiga', 'Color de Hormiga Reserva Natural', 'hotel', 'Vereda San José Alto, cerca del Camino Real', null, null, null, 'https://www.google.com/maps/search/?api=1&query=Color+de+Hormiga+Reserva+Natural+Barichara', 'https://ph.trip.com/hotels/barichara-hotel-detail-9388308/color-de-hormiga-reserva-natural', null, 'Finca-reserva natural de 29 hectáreas a las afueras del pueblo, con habitaciones sencillas y enfoque en naturaleza y gastronomía local.', 'A 29-hectare nature-reserve farm on the edge of town, with simple rooms and a focus on nature and local food.', false, false),
('hotel-venturi', 'Hotel Boutique Venturi', 'hotel', 'Km 17 vía San Gil-Barichara, zona rural', '573017871697', null, null, 'https://www.google.com/maps/search/?api=1&query=Hotel+Boutique+Venturi+Barichara', 'https://www.myboutiquehotel.com/es/boutique-hotels-barichara/hotel-boutique-venturi.html', null, 'Hotel boutique campestre que combina arquitectura colonial y diseño contemporáneo, con restaurante y bar propios.', 'A countryside boutique hotel blending colonial architecture with contemporary design, with its own restaurant and bar.', false, false),
('la-nube-posada', 'La Nube Posada', 'hotel', 'Calle 7 # 7-39, centro histórico', '573103348677', null, null, 'https://www.google.com/maps/search/?api=1&query=La+Nube+Posada+Barichara', 'https://co.hoteles.com/ho547518/la-nube-posada-barichara-colombia', null, 'Posada sencilla y elegante en el casco histórico, con restaurante, bar y servicio de conserjería.', 'A simple, elegant posada in the historic center, with its own restaurant, bar and concierge service.', false, false),
('trip-monkey-hostel', 'Trip Monkey Hostel Barichara', 'hotel', 'Centro del pueblo (zona no verificada)', null, null, null, 'https://www.google.com/maps/search/?api=1&query=Trip+Monkey+Hostel+Barichara', 'https://www.hostelworld.com/hostels/p/310676/trip-monkey-hostel-barichara/', null, 'Hostal de arquitectura colonial con corredor central y zonas comunes, ofrece habitaciones privadas y compartidas tipo backpacker.', 'A colonial-style hostel with a central corridor and common areas, offering both private and backpacker-style shared rooms.', false, false),
('serrania-del-viento', 'Serranía del Viento', 'hotel', 'Km 1.5-2 vía Barichara, ~5 min de la catedral', null, null, null, 'https://www.google.com/maps/search/?api=1&query=Serrania+del+Viento+Barichara', 'https://www.hotels.com/ho925014176', null, 'Alojamiento campestre a minutos del centro con piscina, bar junto a la piscina y jardines, pensado como retiro tranquilo.', 'A countryside stay minutes from the center with a pool, poolside bar and gardens, meant as a quiet retreat.', false, false),
('finca-hotel-buenos-aires', 'Finca Hotel Buenos Aires', 'hotel', 'Vía Barichara Km 1, cruce El Choro a Villanueva', '573002128919', null, null, 'https://www.google.com/maps/search/?api=1&query=Finca+Hotel+Buenos+Aires+Barichara', 'https://www.es.kayak.com/Barichara-Hoteles-Finca-Hotel-Buenos-Aires.640219.ksp', null, 'Eco-hotel tipo finca con habitaciones de balcón privado y baños con paneles solares, rodeado de jardines y piscina.', 'A farm-style eco-hotel with private-balcony rooms and solar-powered bathrooms, surrounded by gardens and a pool.', false, false)
on conflict (slug) do nothing;

-- ===================== RESTAURANTES (15) =====================
insert into public.businesses
  (slug, name, category, zone, whatsapp, instagram, map_url, source_url, description_es, description_en, active, is_sample)
values
('shambala', 'Shambalá', 'restaurante', 'Carrera 7 No. 6-20', '573118926578', null, 'https://www.google.com/maps/search/?api=1&query=Restaurante+Shambala+Barichara', 'https://www.happycow.net/reviews/shambala-barichara-41259', 'Cocina vegetariana y saludable cerca de la plaza principal, conocida por sus salteados, wraps y pastas, con opción de agregar carne o ceviche.', 'Vegetarian, healthy cooking near the main square, known for stir-fries, wraps and pasta, with optional meat or ceviche add-ons.', false, false),
('filomena', 'Filomena', 'restaurante', 'Calle 5 #5-17', '573154559820', '@filomenabarichara', 'https://www.google.com/maps/search/?api=1&query=Filomena+Barichara', 'https://vymaps.com/CO/Filomena-199484/', 'Casa colonial colorida convertida en restaurante informal, especializada en sándwiches a la plancha, hot dogs y hamburguesas con papas.', 'A colorful colonial house turned casual restaurant, specializing in grilled sandwiches, hot dogs and burgers with fries.', false, false),
('noa-restaurante', 'Noa Restaurante', 'restaurante', 'Calle 7 #7-57', '573175042503', null, 'https://www.google.com/maps/search/?api=1&query=Noa+Restaurante+Barichara', 'https://wanderlog.com/place/details/2832935', 'Propuesta ecléctica que mezcla platos de inspiración centro-oriental (falafel, pastas) con opciones colombianas y vegetarianas a precios accesibles.', 'An eclectic menu mixing Middle Eastern-inspired dishes (falafel, pasta) with Colombian and vegetarian options at accessible prices.', false, false),
('el-compa', 'Restaurante El Compa', 'restaurante', 'Calle 5 #4-48', '573162411157', null, 'https://www.google.com/maps/search/?api=1&query=Restaurante+El+Compa+Barichara', 'https://wanderlog.com/place/details/2832914', 'Restaurante sencillo de comida colombiana tradicional con menú del día económico y opción vegetariana bajo solicitud.', 'A simple restaurant serving traditional Colombian food, with an affordable daily set menu and a vegetarian option on request.', false, false),
('bari-comidas', 'Bari Comidas (Bari Dinner)', 'restaurante', 'Carrera 6 #4-64', '573165633212', null, 'https://www.google.com/maps/search/?api=1&query=Bari+Dinner+Barichara', 'https://wanderlog.com/place/details/2832996/bari-dinner', 'Restaurante italiano pequeño y acogedor en el centro, famoso por su pasta fresca hecha a mano y sus pizzas de masa fina cocinadas en plato de barro.', 'A small, cozy Italian restaurant downtown, known for handmade fresh pasta and thin-crust pizzas baked in clay dishes.', false, false),
('shanti-recetas-para-el-alma', 'Shanti Recetas para el Alma', 'restaurante', 'Carrera 7 #6-22', '573183913124', null, 'https://www.google.com/maps/search/?api=1&query=Shanti+Recetas+para+el+alma+Barichara', 'https://uk.trip.com/travel-guide/foods/Barichara-23009-restaurant/Shanti%20Recetas%20para%20el%20alma-34996048', 'Cocina saludable y de autor, en su mayoría vegetariana/vegana con opción de pollo o mariscos, a una cuadra de la plaza principal.', 'Healthy, chef-driven cooking, mostly vegetarian/vegan with chicken or seafood options, a block from the main square.', false, false),
('elvia-cocina-local', 'Elvia Cocina Local', 'restaurante', 'Casa de ~240 años en el centro histórico', null, null, 'https://www.google.com/maps/search/?api=1&query=Elvia+Cocina+Local+Barichara', 'https://www.las2orillas.co/?p=977892', 'Proyecto del chef Rafael Buitrago que reinterpreta ingredientes regionales (mantequilla de Socorro, garbanzo de Curití, trucha de Coromoro) con técnicas contemporáneas.', 'Chef Rafael Buitrago''s project reinterpreting regional ingredients (Socorro butter, Curití chickpeas, Coromoro trout) with contemporary technique.', false, false),
('milana-barichara', 'Milana Barichara', 'restaurante', 'Cupos limitados, reserva previa', null, null, 'https://www.google.com/maps/search/?api=1&query=Milana+Barichara', 'https://wanderlog.com/place/details/8541854/milana-barichara', 'Restaurante de concepto granja a mesa, con pocas mesas y reserva obligatoria, centrado en ingredientes locales frescos.', 'A farm-to-table concept restaurant with few tables and mandatory reservations, focused on fresh local ingredients.', false, false),
('en-el-patio', 'En el Patio', 'restaurante', 'Patio céntrico', null, null, 'https://www.google.com/maps/search/?api=1&query=En+el+Patio+Barichara', 'https://wanderlog.com/place/details/3240424/en-el-patio-barichara', 'Local informal montado en un patio decorado con columpios y plantas, que ofrece arepas, choripán y cerveza artesanal.', 'A casual spot set in a courtyard decorated with swings and plants, serving arepas, choripán and craft beer.', false, false),
('la-nube-restaurante', 'La Nube — Restaurante', 'restaurante', 'Calle 7 # 7-39, centro histórico', '573103348677', null, 'https://www.google.com/maps/search/?api=1&query=La+Nube+Posada+Barichara', 'https://co.hoteles.com/ho547518/la-nube-posada-barichara-colombia', 'Restaurante del hotel-posada La Nube, con menú diseñado por chefs internacionales que fusiona cocina mediterránea con platos tradicionales colombianos.', 'The restaurant of the La Nube posada-hotel, with a menu by international chefs blending Mediterranean cuisine with traditional Colombian dishes.', false, false),
('al-cuoco', 'Al Cuoco (Ristorante al Cuoco)', 'restaurante', 'Cerca del Parque del Cementerio, borde occidental', null, null, 'https://www.google.com/maps/search/?api=1&query=Ristorante+Al+Cuoco+Barichara', 'https://nomadicniko.com/2018/06/25/eating-in-barichara/', 'Restaurante italiano familiar atendido por su propietario, reconocido por preparar pasta artesanal en el mismo local.', 'A family-run Italian restaurant run by its owner, known for making artisan pasta on site.', false, false),
('palacio-de-las-carnes', 'Palacio de las Carnes', 'restaurante', 'Barichara (zona no verificada)', '573182692519', null, 'https://www.google.com/maps/search/?api=1&query=Palacio+de+las+Carnes+Barichara', 'https://wanderlog.com/place/details/3240422', 'Cocina típica santandereana especializada en carnes a la parrilla, arroces y su reconocida arepa de maíz pelado.', 'Traditional Santander cooking specializing in grilled meats, rice dishes and its well-known hominy-corn arepa.', false, false),
('independencia-cocina-sazon', 'Independencia Cocina y Sazón', 'restaurante', 'Terraza con vista panorámica, cerca de Casa La Recoleta', null, null, 'https://www.google.com/maps/search/?api=1&query=Independencia+Cocina+y+Sazon+Barichara', 'https://wanderlog.com/place/details/3005494/independencia-cocina-y-sazón', 'Terrazas al aire libre con vista al paisaje santandereano, ideal para el atardecer, con crepes, sándwiches y pescado fresco.', 'Open-air terraces overlooking the Santander landscape, great at sunset, serving crepes, sandwiches and fresh fish.', false, false),
('nativa-poke-cafe', 'Nativa Poke y Café', 'restaurante', 'Calle 6 #8-70', '573102756602', null, 'https://www.google.com/maps/search/?api=1&query=Nativa+Poke+y+Cafe+Barichara', 'https://wanderlog.com/place/details/2919634/nativa-poke-y-café', 'Café informal especializado en bowls estilo poke con toppings colombianos (aguacate, mango, maíz, zanahoria) y opción de tofu.', 'A casual café specializing in poke-style bowls with Colombian toppings (avocado, mango, corn, carrot) and a tofu option.', false, false),
('finca-san-pedro', 'Finca San Pedro', 'restaurante', 'Vereda Lubigará, km 3.6 vía Barichara-Lubigará', '573174045315', null, 'https://www.google.com/maps/search/?api=1&query=Finca+San+Pedro+Barichara', 'https://wanderlog.com/place/details/12445322/finca-san-pedro-barichara', 'Finca-restaurante vegetariano en las afueras de Barichara, con huerta propia y cocina de granja a mesa a cargo de su propietaria.', 'A vegetarian farm-restaurant on the edge of Barichara, with its own garden and farm-to-table cooking led by its owner.', false, false)
on conflict (slug) do nothing;

-- ===================== EXPERIENCIAS Y TOURS (14) =====================
insert into public.businesses
  (slug, name, category, whatsapp, website, map_url, source_url, price_from, duration, description_es, description_en, active, is_sample)
values
('macondo-project-free-tour', 'Macondo Project — Free Tour Barichara', 'experiencia', '573193504582', 'https://www.civitatis.com/en/barichara/free-tour', null, 'https://noesis.uis.edu.co/entities/publication/61ec26cf-a1e4-4f2c-a689-a90575388677/full', 'Pago a voluntad', '~2 horas', 'Recorrido a pie por el centro histórico de Barichara con guía local que explica la arquitectura en tapia pisada y la historia del pueblo; al final, el visitante decide cuánto pagar.', 'A walking tour of Barichara''s historic center with a local guide explaining the rammed-earth architecture and town history; a pay-what-you-want tour.', false, false),
('alex-barichara-visita-guiada', 'Alex Barichara — Visita guiada', 'experiencia', '573156304696', 'https://www.civitatis.com/en/barichara/guided-walking-tour', null, 'https://noesis.uis.edu.co/entities/publication/61ec26cf-a1e4-4f2c-a689-a90575388677/full', 'Desde US$13', '2.5 horas', 'Caminata guiada por la catedral, el Salto del Mico y la capilla de Santa Bárbara con un guía local independiente (mínimo 3 personas, punto de encuentro en el parque principal).', 'A guided walk past the cathedral, El Salto del Mico and the Santa Bárbara chapel with an independent local guide (minimum 3 people, meeting point at the main square).', false, false),
('civitatis-camino-real-guane', 'Senderismo Camino Real a Guane (Civitatis)', 'experiencia', null, 'https://www.civitatis.com/es/barichara/senderismo-camino-real-guane/', null, 'https://www.civitatis.com/es/barichara/senderismo-camino-real-guane/', 'Desde US$24,96', '~4.5 horas', 'Descenso guiado de unos 8 km por el Camino Real entre Barichara y Guane, con parada en un taller de cerámica de tradición guane y regreso en tuk tuk.', 'A guided ~8 km descent along the Camino Real between Barichara and Guane, with a stop at a Guane-tradition pottery workshop and a tuk-tuk ride back.', false, false),
('guruwalk-barichara-magica', 'Barichara Mágica Free Walking Tour (GuruWalk)', 'experiencia', null, 'https://www.guruwalk.com/es/walks/56788-barichara-magica-free-walking-tour-por-el-pueblo-mas-bonito-de-colombia', null, 'https://www.guruwalk.com/es/walks/56788-barichara-magica-free-walking-tour-por-el-pueblo-mas-bonito-de-colombia', 'Pago a voluntad', '~2 horas', 'Recorrido a pie entre el parque principal, la Casa de la Cultura y un taller de papel artesanal, con pago voluntario al final.', 'A walking tour connecting the main square, the Casa de la Cultura and an artisan paper workshop, pay-what-you-want at the end.', false, false),
('colombia-rafting-barichara-tour', 'Colombia Rafting Expeditions — Barichara Tour', 'experiencia', null, 'https://colombiarafting.com/en/activities/barichara-tour/', null, 'https://colombiarafting.com/en/activities/barichara-tour/', null, 'Día completo', 'Tour de día completo que combina la catedral, la capilla de Santa Bárbara, el Parque de las Aguas, talleres de cerámica y una caminata final por el Camino Real, con guías bilingües.', 'A full-day tour combining the cathedral, the Santa Bárbara chapel, Parque de las Aguas, pottery workshops and a final walk on the Camino Real, with bilingual guides.', false, false),
('bnb-colombia-history-tour', 'BnB Colombia Tours — Historia y Arquitectura de Barichara', 'experiencia', null, 'https://bnbcolombiatours.rezdy.com/436528/walking-the-history-architecture-and-culture-of-barichara', null, 'https://bnbcolombiatours.rezdy.com/436528/walking-the-history-architecture-and-culture-of-barichara', 'Desde US$147,72', '4 horas', 'Recorrido centrado en la arquitectura colonial y la cultura de Barichara, pensado para visitantes internacionales y reservable en plataformas como Pelago.', 'A tour centered on Barichara''s colonial architecture and culture, aimed at international visitors and bookable on platforms like Pelago.', false, false),
('bnb-colombia-coffee-tour', 'BnB Colombia Tours — Barichara Coffee Tour', 'experiencia', null, 'https://bnbcolombiatours.rezdy.com/436819/barichara-coffee-tour', null, 'https://bnbcolombiatours.rezdy.com/436819/barichara-coffee-tour', 'Desde US$279,62', '4 horas', 'Excursión en tuk tuk a una finca cafetera en bosque seco tropical, con explicación del proceso del café y degustación con queso y pan artesanal.', 'A tuk-tuk excursion to a coffee farm in dry tropical forest, explaining the coffee process with a tasting of cheese and artisan bread.', false, false),
('bnb-colombia-private-day-tour', 'BnB Colombia Tours — Barichara Private Day Tour', 'experiencia', null, 'https://bnbcolombiatours.rezdy.com/437889/barichara-private-day-tour-from-bucaramanga', null, 'https://bnbcolombiatours.rezdy.com/437889/barichara-private-day-tour-from-bucaramanga', null, null, 'Tour privado de un día desde Bucaramanga hasta Barichara, operado por una agencia con sede en Bucaramanga para quienes no pernoctan en el pueblo.', 'A private day tour from Bucaramanga to Barichara, run by a Bucaramanga-based agency for visitors not staying overnight in town.', false, false),
('regiones-bike-ancestral-trails', 'Regiones Bike — Ancestral Trails', 'experiencia', null, 'https://regionesbike.rezdy.com/654921/ancestral-trails', null, 'https://regionesbike.rezdy.com/654921/ancestral-trails', null, '3 horas', 'Ruta guiada en bicicleta de montaña por senderos centenarios alrededor de Barichara, con parada en un taller de arcilla y final en una finca con refrescos.', 'A guided mountain-bike route on centuries-old trails around Barichara, with a stop at a clay workshop and a finish at a farm with refreshments.', false, false),
('regiones-bike-tropical-trails', 'Regiones Bike — Tropical Trails', 'experiencia', null, 'https://regionesbike.rezdy.com/654912/tropical-trails', null, 'https://regionesbike.rezdy.com/654912/tropical-trails', null, null, 'Ruta en bicicleta de montaña que atraviesa fincas de café, mandarina y aguacate cerca de la Serranía de los Yariguíes, con ascenso a un mirador.', 'A mountain-bike route through coffee, mandarin and avocado farms near the Yariguíes mountains, climbing to a viewpoint.', false, false),
('colombian-way-camino-real-half-day', 'The Colombian Way — Camino Real Half Day', 'experiencia', null, 'https://thecolombianway.com/en/tour-store/tours/barichara/camino-real-half-day/', null, 'https://thecolombianway.com/en/tour-store/tours/barichara/camino-real-half-day/', null, '4 horas', 'Caminata guiada en inglés de medio día por el antiguo sendero empedrado que conecta Barichara con Guane.', 'A half-day English-guided walk along the old stone path connecting Barichara with Guane.', false, false),
('colombian-way-guane-full-day', 'The Colombian Way — Guane & Barichara Full Day', 'experiencia', null, 'https://thecolombianway.com/en/tour-store/tours/barichara/guane-barichara-full-day/', null, 'https://thecolombianway.com/en/tour-store/tours/barichara/guane-barichara-full-day/', null, 'Día completo', 'Tour de un día completo que combina la visita a Barichara con el corregimiento de Guane, generalmente conectados por el Camino Real.', 'A full-day tour combining Barichara with the Guane township, usually connected via the Camino Real.', false, false),
('airbnb-birdwatching-barichara', 'Airbnb Experience — Birdwatching Tour', 'experiencia', null, 'https://www.airbnb.com.au/experiences/7221989', null, 'https://www.airbnb.com.au/experiences/7221989', null, 'Caminata de 7.7 km', 'Caminata de avistamiento de aves por senderos ancestrales guane entre Villanueva y Barichara, con anfitrión experto y desayuno al llegar.', 'A birdwatching walk on ancestral Guane trails between Villanueva and Barichara, with an expert host and breakfast on arrival.', false, false),
('airbnb-historical-tour-barichara', 'Airbnb Experience — Historical and Architectural Tour', 'experiencia', null, 'https://www.airbnb.com.au/experiences/6758421', null, 'https://www.airbnb.com.au/experiences/6758421', null, null, 'Recorrido a pie por la arquitectura en piedra y tapia de Barichara, sus templos y miradores, reservable directamente en Airbnb.', 'A walking tour of Barichara''s stone and rammed-earth architecture, churches and viewpoints, bookable directly on Airbnb.', false, false)
on conflict (slug) do nothing;

-- ===================== TALLERES (3), TRANSPORTE (2), EVENTOS (1), COMERCIOS (1) =====================
insert into public.businesses
  (slug, name, category, zone, whatsapp, website, map_url, source_url, price_from, duration, description_es, description_en, active, is_sample)
values
('taller-papel-san-lorenzo', 'Taller de Papel Barichara (Fundación San Lorenzo)', 'taller', 'Carrera 5 No. 2-88', '57327267234', 'tallerdepapelbarichara.com', null, 'https://nomadicniko.com/2018/06/26/barichara-paper-workshop/', 'Entrada $3.000 COP', '~30 min (visita) / ~2 horas (ruta completa)', 'Taller de un colectivo de mujeres que elabora papel a mano con fibra de fique y otras plantas de la región; se puede visitar o reservar la ruta completa del proceso.', 'A women-led workshop making paper by hand from fique fiber and other local plants; open for a short visit or a full process tour.', false, false),
('de-la-tierra-casa-taller', 'De la Tierra Casa Taller', 'taller', 'Barichara (zona no verificada)', null, 'https://www.airbnb.com/experiences/336926', null, 'https://www.elespectador.com/turismo/barichara-una-conexion-con-la-vida-y-la-tierra-article-907417/', null, null, 'Casa taller de Santiago Rivero y Lina Pieruccini dedicada a la pintura con tierras y pigmentos naturales del cañón.', 'A workshop house run by Santiago Rivero and Lina Pieruccini, focused on painting with the canyon''s natural earth pigments.', false, false),
('civitatis-taller-artesania', 'Taller de artesanía en Barichara (Civitatis)', 'taller', null, null, 'https://www.civitatis.com/es/barichara/taller-artesania-barichara/', null, 'https://www.civitatis.com/es/barichara/taller-artesania-barichara/', 'Desde US$33,85', '2 a 2.5 horas', 'Taller práctico reservable en Civitatis para aprender una técnica artesanal tradicional de la región, con traslado incluido desde el parque principal.', 'A hands-on workshop bookable via Civitatis to learn a traditional regional craft technique, with transport included from the main square.', false, false),
('cotrasangil', 'CotraSangil', 'transporte', null, '573151594699', 'cotrasangil.com', null, 'https://bidsfactory.com/en/companies/cotrasangil', 'Desde COP $6.500', null, 'Cooperativa de transporte intermunicipal con buses regulares entre San Gil y Barichara cada 20-30 minutos; el servicio formal más usado en esta ruta.', 'An intermunicipal transport cooperative running regular buses between San Gil and Barichara every 20-30 minutes; the most-used formal service on this route.', false, false),
('daytrip-transfers', 'Daytrip', 'transporte', null, null, 'daytrip.com', null, 'https://daytrip.com/en/transfers/bucaramanga-co/barichara-co', 'Desde USD $34', null, 'Traslados privados puerta a puerta entre Bucaramanga o San Gil y Barichara, con conductor profesional y vehículo según número de pasajeros.', 'Private door-to-door transfers between Bucaramanga or San Gil and Barichara, with a professional driver and vehicle sized to the group.', false, false),
('festiver-barichara', 'Barichara Green Film Festival (FESTIVER)', 'evento', null, null, 'https://filmmakers.festhome.com/f/festiver', null, 'https://filmmakers.festhome.com/f/festiver', null, 'Finales de septiembre (16ª edición: 24-27 sept. 2026)', 'Festival de cine ambiental creado por los actores Toto Vega y Nórida Rodríguez, con proyecciones y actividades académicas y artísticas sobre conciencia ecológica.', 'An environmental film festival created by actors Toto Vega and Nórida Rodríguez, with screenings and academic/artistic activities on ecological awareness.', false, false),
('albahaca-hospedaje-tienda', 'Albahaca Hospedaje y Tienda', 'comercio', 'Calle 10 No. 7-54, Barrio La Loma', null, null, null, 'https://www.atrapalo.com/hoteles/1266699-0_albahaca-hospedaje-tienda', null, null, 'Hospedaje en una casa centenaria que incluye una pequeña tienda y taller propio de aceites y cremas artesanales.', 'Lodging in a century-old house with a small shop and workshop making artisan oils and creams.', false, false)
on conflict (slug) do nothing;

-- ===================== Desactivar negocios genéricos no reconfirmados =====================
-- De la carga inicial ("15 mejores" sin verificación profunda): se mantienen
-- en la base de datos pero ocultos, por si luego se quieren reconfirmar o
-- contactar igual. No se borran.
update public.businesses set active = false
where slug in (
  'hotel-terra-barichara','casa-oniri','posada-villa-paula','la-juanita-hostel','corata','achiotte',
  'restaurante-terra','la-puerta-secret-kitchen','epice','frenchut','gringo-mikes','mija','el-puntal'
);
